version: '3'
services:
  app:
    image: antenna_app:latest
#    build:
#      context: .
#    env_file:
#      - ./environments/db.env
    command: bundle exec rails s
#    volumes:
#      - .:/webapp
#      - public-data:/webapp/public
#      - tmp-data:/webapp/tmp
#      - log-data:/webapp/log
    ports:
      - 3000:3000
#    depends_on:
#      - db
    deploy:
      replicas: 2
      update_config:
#        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
#  db:
#    image: mysql:5.7
#    env_file:
#      - ./environments/db.env
#    volumes:
#      - db-data:/var/lib/mysql
#  web:
#    build:
#      context: containers/nginx
#    volumes:
#      - public-data:/webapp/public
#      - tmp-data:/webapp/tmp
#    ports:
#      - 80:80
#    depends_on:
#      - app
#volumes:
#  public-data:
#  tmp-data:
#  log-data:
#  db-data:
